### ISSUE TITLE
Update to v3!

### ISSUE THREAD

**Issue by Sidmaz666** [mrdotb/vim-tailwindcss#1]
Hey, I appreciate your work it's an amazing plugin and I use it daily, it would be nice if the plugin also includes tailwindcss version 3 classes.

Thank You!

**Comment by mrdotb** [comment]
Hello I wanted to add support for v3.
After investigation v3 is only JIT not a simple css file anymore so I can't generate the completion with my [script](https://github.com/mrdotb/vim-tailwindcss/blob/master/generate_data.exs) anymore.

I suggest to look at https://github.com/rodrigore/coc-tailwind-intellisense

**Comment by Sidmaz666** [comment]
Thank you for giving your time and enlightening me on the issue. 

However the reason I'm using this plugin because coc-tailwind-intellisense and coc-tailwindcss doesn't work for me.
So, yeah I think I have to finally figure out how to make coc-tailwind-intellisense work.

**Comment by mrdotb** [comment]
I'm using coc for other auto completion
Last time I try coc tailwind I think it did not work out of the box and I keep using mine but with some tinker it should work.

**Comment by Sidmaz666** [comment]
Well I'm gonna try coc-tailwind soon, hope it works right out of the box 🙃 last time I turned on all the debugging options but didn't caught the issue.
